services:
  viabtc-ubuntu:
    build: .
    container_name: viabtc-ubuntu-container
    image: viabtc-ubuntu-image
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - mysql
      - kafka

  mysql:
    image: mysql:latest
    restart: always
    container_name: viabtc-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trade_history
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ../sql:/docker-entrypoint-initdb.d

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: viabtc-zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: viabtc-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "balances:1:1,orders:1:1,deals:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

volumes:
  mysql_data: